### ISSUE TITLE
Input has NaN

### ISSUE THREAD

**Issue by kfe-code27** [Zafar-Lab/scDREAMER#7]
I'm getting the following issue after running scDREAMER. I can't figure out where the latent_matrix is stored and had no issue running other integration pipelines on this dataset.

```
Reading data
WARNING: adata.X seems to be already log-transformed.
encoder input shape  Tensor("concat:0", shape=(?, 2013), dtype=float32)
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
decoder input shape  Tensor("concat_2:0", shape=(?, 23), dtype=float32)
KL gaussian z Tensor("mul_10:0", shape=(?,), dtype=float32)
KL gaussian l Tensor("mul_9:0", shape=(?,), dtype=float32)
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

scDREAMER on DataSet /labs/bhasinlab/keferg2/scanpy_obj.h5ad ... 
2024-08-07 12:08:24.319632: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
Epoch : [0] ,  a_loss = 235.5779
Epoch : [10] ,  a_loss = 202.3737
Epoch : [20] ,  a_loss = 201.5301
Epoch : [30] ,  a_loss = 199.0259
Epoch : [40] ,  a_loss = 197.0664
Epoch : [50] ,  a_loss = 192.4374
Epoch : [60] ,  a_loss = 206.9719
Epoch : [69] ,  a_loss = 212.6629
Epoch : [69] ,  a_loss = 212.6629
latent_matrix shape (628590, 10)
(628590,)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <timed exec>:21

File ~/scDREAMER/scDREAMER/scDREAMER/model.py:221, in train_cluster(self)
    217     if (ep %10 == 0):
    218         print("Epoch : [%d] ,  a_loss = %.4f" #, d_loss: %.4f ,  db_loss: %.4f" 
    219          % (ep, np.mean(a_loss_epoch)))#, np.mean(d2_loss_epoch), np.mean(db_loss_epoch)))
--> 221 self.eval_cluster_on_test(self.epoch)

File ~/scDREAMER/scDREAMER/scDREAMER/utils.py:160, in eval_cluster_on_test(self, epoch)
    157 Ann.obsm['final_embeddings'] = latent_matrix
    158 Ann.obs['group'] = labels.astype(str)
--> 160 sc.pp.neighbors(Ann, use_rep = 'final_embeddings') #use_rep = 'final_embeddings'
    161 sc.tl.umap(Ann)
    162 img = sc.pl.umap(Ann, color = 'group', frameon = False) # cells

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:139, in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, key_added, copy)
    137     adata._init_as_actual(adata.copy())
    138 neighbors = Neighbors(adata)
--> 139 neighbors.compute_neighbors(
    140     n_neighbors=n_neighbors,
    141     knn=knn,
    142     n_pcs=n_pcs,
    143     use_rep=use_rep,
    144     method=method,
    145     metric=metric,
    146     metric_kwds=metric_kwds,
    147     random_state=random_state,
    148 )
    150 if key_added is None:
    151     key_added = 'neighbors'

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:794, in Neighbors.compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    792     X = pairwise_distances(X, metric=metric, **metric_kwds)
    793     metric = 'precomputed'
--> 794 knn_indices, knn_distances, forest = compute_neighbors_umap(
    795     X, n_neighbors, random_state, metric=metric, metric_kwds=metric_kwds
    796 )
    797 # very cautious here
    798 try:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:305, in compute_neighbors_umap(X, n_neighbors, random_state, metric, metric_kwds, angular, verbose)
    301     from umap.umap_ import nearest_neighbors
    303 random_state = check_random_state(random_state)
--> 305 knn_indices, knn_dists, forest = nearest_neighbors(
    306     X,
    307     n_neighbors,
    308     random_state=random_state,
    309     metric=metric,
    310     metric_kwds=metric_kwds,
    311     angular=angular,
    312     verbose=verbose,
    313 )
    315 return knn_indices, knn_dists, forest

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/umap/umap_.py:328, in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, low_memory, use_pynndescent, n_jobs, verbose)
    325     n_trees = min(64, 5 + int(round((X.shape[0]) ** 0.5 / 20.0)))
    326     n_iters = max(5, int(round(np.log2(X.shape[0]))))
--> 328     knn_search_index = NNDescent(
    329         X,
    330         n_neighbors=n_neighbors,
    331         metric=metric,
    332         metric_kwds=metric_kwds,
    333         random_state=random_state,
    334         n_trees=n_trees,
    335         n_iters=n_iters,
    336         max_candidates=60,
    337         low_memory=low_memory,
    338         n_jobs=n_jobs,
    339         verbose=verbose,
    340         compressed=False,
    341     )
    342     knn_indices, knn_dists = knn_search_index.neighbor_graph
    344 if verbose:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/pynndescent/pynndescent_.py:722, in NNDescent.__init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_degree_multiplier, diversify_prob, n_search_trees, tree_init, init_graph, init_dist, random_state, low_memory, max_candidates, n_iters, delta, n_jobs, compressed, parallel_batch_queries, verbose)
    719 else:
    720     copy_on_normalize = False
--> 722 data = check_array(data, dtype=np.float32, accept_sparse="csr", order="C")
    723 self._raw_data = data
    725 if not tree_init or n_trees == 0 or init_graph is not None:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/sklearn/utils/validation.py:921, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
    915         raise ValueError(
    916             "Found array with dim %d. %s expected <= 2."
    917             % (array.ndim, estimator_name)
    918         )
    920     if force_all_finite:
--> 921         _assert_all_finite(
    922             array,
    923             input_name=input_name,
    924             estimator_name=estimator_name,
    925             allow_nan=force_all_finite == "allow-nan",
    926         )
    928 if ensure_min_samples > 0:
    929     n_samples = _num_samples(array)

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/sklearn/utils/validation.py:161, in _assert_all_finite(X, allow_nan, msg_dtype, estimator_name, input_name)
    144 if estimator_name and input_name == "X" and has_nan_error:
    145     # Improve the error message on how to handle missing values in
    146     # scikit-learn.
    147     msg_err += (
    148         f"\n{estimator_name} does not accept missing values"
    149         " encoded as NaN natively. For supervised learning, you might want"
   (...)
    159         "#estimators-that-handle-nan-values"
    160     )
--> 161 raise ValueError(msg_err)

ValueError: Input contains NaN.
```

**Comment by kfe-code27** [comment]
`Reading data
WARNING: adata.X seems to be already log-transformed.
encoder input shape  Tensor("concat:0", shape=(?, 2013), dtype=float32)
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
decoder input shape  Tensor("concat_2:0", shape=(?, 23), dtype=float32)
KL gaussian z Tensor("mul_10:0", shape=(?,), dtype=float32)
KL gaussian l Tensor("mul_9:0", shape=(?,), dtype=float32)
WARNING:tensorflow:From /home/keferg2/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:1260: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

scDREAMER on DataSet /labs/bhasinlab/keferg2/scanpy_obj.h5ad ... 
2024-08-07 12:08:24.319632: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:388] MLIR V1 optimization pass is not enabled
Epoch : [0] ,  a_loss = 235.5779
Epoch : [10] ,  a_loss = 202.3737
Epoch : [20] ,  a_loss = 201.5301
Epoch : [30] ,  a_loss = 199.0259
Epoch : [40] ,  a_loss = 197.0664
Epoch : [50] ,  a_loss = 192.4374
Epoch : [60] ,  a_loss = 206.9719
Epoch : [69] ,  a_loss = 212.6629
Epoch : [69] ,  a_loss = 212.6629
latent_matrix shape (628590, 10)
(628590,)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File <timed exec>:21

File ~/scDREAMER/scDREAMER/scDREAMER/model.py:221, in train_cluster(self)
    217     if (ep %10 == 0):
    218         print("Epoch : [%d] ,  a_loss = %.4f" #, d_loss: %.4f ,  db_loss: %.4f" 
    219          % (ep, np.mean(a_loss_epoch)))#, np.mean(d2_loss_epoch), np.mean(db_loss_epoch)))
--> 221 self.eval_cluster_on_test(self.epoch)

File ~/scDREAMER/scDREAMER/scDREAMER/utils.py:160, in eval_cluster_on_test(self, epoch)
    157 Ann.obsm['final_embeddings'] = latent_matrix
    158 Ann.obs['group'] = labels.astype(str)
--> 160 sc.pp.neighbors(Ann, use_rep = 'final_embeddings') #use_rep = 'final_embeddings'
    161 sc.tl.umap(Ann)
    162 img = sc.pl.umap(Ann, color = 'group', frameon = False) # cells

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:139, in neighbors(adata, n_neighbors, n_pcs, use_rep, knn, random_state, method, metric, metric_kwds, key_added, copy)
    137     adata._init_as_actual(adata.copy())
    138 neighbors = Neighbors(adata)
--> 139 neighbors.compute_neighbors(
    140     n_neighbors=n_neighbors,
    141     knn=knn,
    142     n_pcs=n_pcs,
    143     use_rep=use_rep,
    144     method=method,
    145     metric=metric,
    146     metric_kwds=metric_kwds,
    147     random_state=random_state,
    148 )
    150 if key_added is None:
    151     key_added = 'neighbors'

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:794, in Neighbors.compute_neighbors(self, n_neighbors, knn, n_pcs, use_rep, method, random_state, write_knn_indices, metric, metric_kwds)
    792     X = pairwise_distances(X, metric=metric, **metric_kwds)
    793     metric = 'precomputed'
--> 794 knn_indices, knn_distances, forest = compute_neighbors_umap(
    795     X, n_neighbors, random_state, metric=metric, metric_kwds=metric_kwds
    796 )
    797 # very cautious here
    798 try:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/scanpy/neighbors/__init__.py:305, in compute_neighbors_umap(X, n_neighbors, random_state, metric, metric_kwds, angular, verbose)
    301     from umap.umap_ import nearest_neighbors
    303 random_state = check_random_state(random_state)
--> 305 knn_indices, knn_dists, forest = nearest_neighbors(
    306     X,
    307     n_neighbors,
    308     random_state=random_state,
    309     metric=metric,
    310     metric_kwds=metric_kwds,
    311     angular=angular,
    312     verbose=verbose,
    313 )
    315 return knn_indices, knn_dists, forest

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/umap/umap_.py:328, in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, low_memory, use_pynndescent, n_jobs, verbose)
    325     n_trees = min(64, 5 + int(round((X.shape[0]) ** 0.5 / 20.0)))
    326     n_iters = max(5, int(round(np.log2(X.shape[0]))))
--> 328     knn_search_index = NNDescent(
    329         X,
    330         n_neighbors=n_neighbors,
    331         metric=metric,
    332         metric_kwds=metric_kwds,
    333         random_state=random_state,
    334         n_trees=n_trees,
    335         n_iters=n_iters,
    336         max_candidates=60,
    337         low_memory=low_memory,
    338         n_jobs=n_jobs,
    339         verbose=verbose,
    340         compressed=False,
    341     )
    342     knn_indices, knn_dists = knn_search_index.neighbor_graph
    344 if verbose:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/pynndescent/pynndescent_.py:722, in NNDescent.__init__(self, data, metric, metric_kwds, n_neighbors, n_trees, leaf_size, pruning_degree_multiplier, diversify_prob, n_search_trees, tree_init, init_graph, init_dist, random_state, low_memory, max_candidates, n_iters, delta, n_jobs, compressed, parallel_batch_queries, verbose)
    719 else:
    720     copy_on_normalize = False
--> 722 data = check_array(data, dtype=np.float32, accept_sparse="csr", order="C")
    723 self._raw_data = data
    725 if not tree_init or n_trees == 0 or init_graph is not None:

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/sklearn/utils/validation.py:921, in check_array(array, accept_sparse, accept_large_sparse, dtype, order, copy, force_all_finite, ensure_2d, allow_nd, ensure_min_samples, ensure_min_features, estimator, input_name)
    915         raise ValueError(
    916             "Found array with dim %d. %s expected <= 2."
    917             % (array.ndim, estimator_name)
    918         )
    920     if force_all_finite:
--> 921         _assert_all_finite(
    922             array,
    923             input_name=input_name,
    924             estimator_name=estimator_name,
    925             allow_nan=force_all_finite == "allow-nan",
    926         )
    928 if ensure_min_samples > 0:
    929     n_samples = _num_samples(array)

File ~/miniconda3/envs/scdreamer_git/lib/python3.9/site-packages/sklearn/utils/validation.py:161, in _assert_all_finite(X, allow_nan, msg_dtype, estimator_name, input_name)
    144 if estimator_name and input_name == "X" and has_nan_error:
    145     # Improve the error message on how to handle missing values in
    146     # scikit-learn.
    147     msg_err += (
    148         f"\n{estimator_name} does not accept missing values"
    149         " encoded as NaN natively. For supervised learning, you might want"
   (...)
    159         "#estimators-that-handle-nan-values"
    160     )
--> 161 raise ValueError(msg_err)

ValueError: Input contains NaN.`

**Comment by ajitashree** [comment]
Dear author, Thank you being interested in scDREAMER. The latent matrix is denoted by latent_matrix variable in the code.
Ann.obsm['final_embeddings'] = **latent_matrix**

We suggest you run scDREAMER for recommended 200-250 epochs for a better training. You may let us know if the issue still persists. Could you also share no of cells and no of batches in your dataset?

**Comment by kfe-code27** [comment]
I have epoch set to 250. The data set has 628590 cells × 31520 features with 13 batches. This is actually a subset of my dataset which has a lot more cells but the same number of batches. This issue is persistent and seems to be after scDreamer encoder and decoder have finished running and with the def eval_cluster_on_test(self, epoch): function perhaps.

**Comment by ajitashree** [comment]
Could you please provide us with the data source? so that, we can try to debug it at our end.

**Comment by kfe-code27** [comment]
Yes. I will likely have to deidentify the data. What is the best way to send you the data source?

**Comment by kfe-code27** [comment]
I was able to solve this by lowering the learning rate

**Comment by ajitashree** [comment]
Thats great, you are able to run the method. Yes, we do have recommendations of using lower learning rates for the bigger datasets. https://scdreamer.readthedocs.io/en/latest/scDREAMER_Atlas_level_integration.html
